### ISSUE TITLE
Critical chance values for warrior.

### ISSUE THREAD

**Issue by Simonich** [Metalica/TeraWoW-1.12.1.-Database#4]
The critical chance agility gives you is incorrect, it should be 0.05% per agility point for warrior.
In Addition, there should be a basic critical strike you start with (it should be 5%)

(etc if a warrior has 3 agility, he should have 5% + (3x0.05%) = 5.15% critical strike chance

**Comment by Metalica** [comment]
Aplied patch. Let's see how it goes.

**Comment by Simonich** [comment]
Fixed

(There is a possibility there's more crit than it should have)

**Comment by Metalica** [comment]
Few %. Closing the report.
